### ISSUE TITLE
Deal with conflicts when two stubbed modules have the same function name/arity

### ISSUE THREAD

**Issue by brandonjoyce** [sonerdy/double#29]
If two modules are stubbed who have the same module/function name:
```
io_stub = double(IO) |> allow(:puts, fn(_) -> :ok end)
other_stub = double(Other) |> allow(:puts, fn(_) -> :ok end)
```
Then a call to either stub's `puts/1` function will send the test process a message `{:puts, "arg"}`.  This would make it difficult to determine for certain which stub is being called.  For example with assert_receive:
```
assert_receive({:puts, arg}) # Which stub is being called?
```

Adding the module name to the message makes sense, but is a breaking change ex: `{IO, :puts, args}`.

However, we've been considering adding a `stub` alias for `allow` anyway since that was mostly inspired by RSpec, but it isn't really the same.   We could adopt this new 3-tuple behavior when the `stub` function is used, and stick with the 2-tuple for `allow` calls.

**Comment by JonRowe** [comment]
Related to this, but its currently not possible to get double to allow a function call that conflicts with a "default" import. (The actual implementation works fine however).

```
    handler =
      SlackNotification
      |> Double.double()
      |> Double.allow(:send, fn _, _ -> :ok end)
```

```
 ** (EXIT from #PID<0.465.0>) exited in: GenServer.call(Double.Eval, {:eval, "defmodule :SlackNotificationDouble674 do\n  def send(a, b) do\n    test_pid = Double.Registry.whereis_test(\"SlackNotificationDouble674\")\nsend(test_pid, {:send, a, b})\npid = Double.Registry.whereis_double(\"SlackNotificationDouble674\")\nfunc_list = Double.func_list(pid)\nDouble.FuncList.apply(func_list, :send, [a, b])\n\n  end\n\nend"}, 5000)
         ** (EXIT) an exception was raised:
             ** (CompileError) nofile:2: imported Kernel.send/2 conflicts with local function
                 (elixir) src/elixir_locals.erl:93: :elixir_locals."-ensure_no_import_conflict/3-lc$^0/1-0-"/2
                 (elixir) src/elixir_locals.erl:94: anonymous fn/3 in :elixir_locals.ensure_no_import_conflict/3
                 (elixir) src/elixir_def.erl:65: :elixir_def.fetch_definitions/2
                 (elixir) src/elixir_module.erl:93: :elixir_module.compile/5
                 (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
                 (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
                 (elixir) src/elixir.erl:258: :elixir.eval_forms/4
                 (elixir) lib/code.ex:232: Code.eval_string/3
                 (double) lib/double/eval.ex:24: Double.Eval.handle_call/3
                 (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
